server { 
	listen 80; 
	server_name php2; 
	
	root /var/www/php2; 
	index info.php index.php index.html; 
	
	location / { 
		try_files $uri $uri/ =404; 
	} 
	
	location ~ \.php$ { 
		include snippets/fastcgi-php.conf; 
		fastcgi_pass unix:/run/php/php8.2-fpm.sock; 
	} 
}

