services:
  mysql:
    image: mysql:8.0
    container_name: wp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_net

  wordpress:
    image: wordpress:php8.4-fpm
    container_name: wp_php
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - wp_data:/var/www/html
    networks:
      - wp_net

  nginx:
    image: nginx:stable
    container_name: wp_nginx
    depends_on:
      - wordpress
    ports:
      - "8080:80"
    volumes:
      - wp_data:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    networks:
      - wp_net

  openresty:
    image: openresty/openresty:alpine
    container_name: wp_openresty
    depends_on:
      - nginx
    ports:
      - "80:80"
    volumes:
      - ./openresty/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - wp_net

volumes:
  db_data:
  wp_data:

networks:
  wp_net:
